### ISSUE TITLE
 shufflewzc_faker2_main

### ISSUE THREAD

**Issue by thiswangDeFa** [shufflewzc/faker2#109]

**Comment by thiswangDeFa** [comment]
禁用重复任务日志
shufflewzc_faker2_main
Traceback (most recent call last):
  File "/ql/data/scripts/shufflewzc_faker2_main/jd_identical.py", line 192, in <module>
    filter_list, res_list = filter_res_sub(tasklist)
  File "/ql/data/scripts/shufflewzc_faker2_main/jd_identical.py", line 70, in filter_res_sub
    if task.get("command").find(sub) == -1:
AttributeError: 'str' object has no attribute 'get'
