### ISSUE TITLE
获取互助码, 错误! TypeError: Cannot read properties of undefined (reading 'bizCode')  

### ISSUE THREAD

**Issue by cn-404-not-found** [shufflewzc/faker2#123]
这是什么原因？没有bizCode依赖吗，但是我手动安装是装不上这个依赖的啊，提示这个

开始安装依赖 bizCode，开始时间 2023-07-19 00:52:38

  bizCode (no such package):
    required by: world[bizCode]

**Comment by sunjialinsun** [comment]
我也遇到这个问题， 群晖docker，正式版 v2.16.5， linux依赖安装都失败了。 不知道是否和依赖安装失败有关。

种豆得豆-初始失败:  {"code":"1","echo":"no access"}

❗️获取互助码, 错误!
TypeError: Cannot read properties of undefined (reading 'bizCode')
    at /ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:481:25
    at got.post.then.message (/ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:677:5772)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
======账号1结束======
