### ISSUE TITLE
利用jshook自动更新JD_COOKIE

### ISSUE THREAD

**Issue by J3n5en** [shufflewzc/faker2#132]
使用 https://jshook.org/ 加载脚本，实现每次打开手机京东app自动提交JD_COOKIE到青龙

脚本地址: https://gist.github.com/J3n5en/34e122cec18930983273a740025c63d8

https://github.com/shufflewzc/faker2/assets/10610925/b8397d03-ffd9-4e64-899d-8a38b37db5ca

**Comment by golangboy** [comment]
输入账号密码，直接返回cookie 
https://github.com/golangboy/jd-cookie

**Comment by jjwjs** [comment]
脚本链接打不开

**Comment by dong50252409** [comment]
这样看 可以用安卓模拟器 然后 app分身安装 登陆多个账号 然后 脚本控制自动切换app登陆 实现自动提交

**Comment by MooreFoss** [comment]
用不了啊

**Comment by MooreFoss** [comment]
可以用了，感谢

**Comment by devnakx** [comment]
是我 jshook 版本不对么，我把脚本 copy 下来导入 jshook 后运行一直提示语法错误，让 Copilot 给我改了下，但到最后直接报错`Java 未定义`
```
[2024-04-27 13:14:51][com.jingdong.app.mall]: JavaScript exception: org.mozilla.javascript.EcmaError: ReferenceError: "Java" 未定义. (JsEngine#1(eval)#75)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source:9)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source:14)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(Unknown Source:14)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(Unknown Source:95)
	at org.mozilla.javascript.ScriptRuntime.name(Unknown Source:21)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source:1451)
	at script(JsEngine#1(eval):75)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source:56)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:20)
	at org.mozilla.javascript.ArrowFunction.call(Unknown Source:11)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source:5799)
	at script(JsEngine:1)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source:56)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:20)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source:0)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source:33)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source:15)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(Unknown Source:95)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(Unknown Source:7)
	at org.mozilla.javascript.InterfaceAdapter.ʿʽʼˆˈˆ(Unknown Source:0)
	at ˎʾˋˉʾ.run(Unknown Source:13)
	at org.mozilla.javascript.Context.call(Unknown Source:5)
	at org.mozilla.javascript.ContextFactory.call(Unknown Source:0)
	at org.mozilla.javascript.InterfaceAdapter.invoke(Unknown Source:12)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(Unknown Source:95)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy8.run(Unknown Source)
	at ʿˎˏˈˏˎ.ʿʽʼˆˈˆ(Unknown Source:324)
	at ʿˎˏˈˏˎ.ʻˎʻˆ(Unknown Source:3)
	at ˏˊʼʿיʼˑ$ˋʾʾˆˎˋˉˊ.ʻʻˆˊˉʼˋ(SourceFile:80)
	at ˏˎˋˏ.ˉʻˏˉˈʿˉˆʿ(Unknown Source:8)
	at יˈˏʼʼˊˏˈ.run(Unknown Source:100)
	at ʽˆˎʻיˎ.run(Unknown Source:11)
	at ʾˏʿˊˊˊʽʻ.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.ʿʽʼˆˈˆ$ʿʽʼˆˈˆ.run(SourceFile:79)
```
