### ISSUE TITLE
Error: Cannot find module错误

### ISSUE THREAD

**Issue by wangmingyu84** [shufflewzc/faker2#139]
东东农场相关的脚本，最近两周出现以下错误（京豆有类似的错误，只不过module的名字不同）：
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './function/krgetToken'
Require stack:
- /ql/data/scripts/shufflewzc_faker2/jd_fruit_watering.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/ql/data/scripts/shufflewzc_faker2/jd_fruit_watering.js:8:1539)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/shufflewzc_faker2/jd_fruit_watering.js' ]

两周前可以正常使用

**Comment by Shadow-wei** [comment]
解决了吗？

**Comment by wangmingyu84** [comment]
> 解决了吗？

没有呢，工具和仓库都没动过，突然就各种问题了，之前用了大半年都好好的

**Comment by Shadow-wei** [comment]
不知道什么情况，你一天可以领多少豆




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月4日(星期一) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shufflewzc/faker2] Error: Cannot find module错误 (Issue #139)





  
解决了吗？
  
没有呢，工具和仓库都没动过，突然就各种问题了，之前用了大半年都好好的

**Comment by testwhite** [comment]
我的也是这样

**Comment by testwhite** [comment]
有人解决吗？看来不只是部分人的问题，应该都有问题吧。
![image](https://github.com/shufflewzc/faker2/assets/31587423/0602d4c2-59b2-4b64-9a61-753f0ede7750)

**Comment by testwhite** [comment]
已经解决了：https://www.playezu.com/766733.html   我的按照流程操作可以了。

**Comment by testwhite** [comment]
> 东东农场相关的脚本，最近两周出现以下错误（京豆有类似的错误，只不过module的名字不同）： node:internal/modules/cjs/loader:1080 throw err; ^
> 
> Error: Cannot find module './function/krgetToken' Require stack:
> 
> * /ql/data/scripts/shufflewzc_faker2/jd_fruit_watering.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>   at Module._load (node:internal/modules/cjs/loader:922:27)
>   at Module.require (node:internal/modules/cjs/loader:1143:19)
>   at require (node:internal/modules/cjs/helpers:110:18)
>   at Object. (/ql/data/scripts/shufflewzc_faker2/jd_fruit_watering.js:8:1539)
>   at Module._compile (node:internal/modules/cjs/loader:1256:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>   at Module.load (node:internal/modules/cjs/loader:1119:32)
>   at Module._load (node:internal/modules/cjs/loader:960:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/ql/data/scripts/shufflewzc_faker2/jd_fruit_watering.js' ]
> 
> 两周前可以正常使用

已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。

**Comment by testwhite** [comment]
> 解决了吗？

已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。

**Comment by testwhite** [comment]
> > 解决了吗？
> 
> 没有呢，工具和仓库都没动过，突然就各种问题了，之前用了大半年都好好的

已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。

**Comment by Shadow-wei** [comment]
你们一天大约多少豆

**Comment by toobye** [comment]
> > > 解决了吗？
> > 
> > 
> > 没有呢，工具和仓库都没动过，突然就各种问题了，之前用了大半年都好好的
> 
> 已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。

试过了，还是不行。。。

**Comment by wangmingyu84** [comment]
> > > > 解决了吗？
> > > 
> > > 
> > > 没有呢，工具和仓库都没动过，突然就各种问题了，之前用了大半年都好好的
> > 
> > 
> > 已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。
> 
> 试过了，还是不行。。。

按照链接里面的方法解决了，京豆和农场都好了。
因为全部重新拉了仓库，所以会出现其他module不存在的情况，安装一下就好了。

**Comment by toobye** [comment]
> > > > > 解决了吗？
> > > > 
> > > > 
> > > > 没有呢，工具和仓库都没动过，突然就各种问题了，之前用了大半年都好好的
> > > 
> > > 
> > > 已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。
> > 
> > 
> > 试过了，还是不行。。。
> 
> 按照链接里面的方法解决了，京豆和农场都好了。 因为全部重新拉了仓库，所以会出现其他module不存在的情况，安装一下就好了。

我甚至重装了青龙面板都不行，把faker2换成了faker3

**Comment by yanstu** [comment]
> > 解决了吗？
> 
> 已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。

有用👍感谢

**Comment by testwhite** [comment]
> > > 解决了吗？
> > 
> > 
> > 已经解决了：https://www.playezu.com/766733.html 我的按照流程操作可以了。
> 
> 有用👍感谢

不客气。

**Comment by leeran2017** [comment]
我按照之前说的删除并重新拉取的方法不成功。但是我根据日志得知是function目录下缺文件，我就搜索一些git上的相应文件并下载，最后成功解决该问题。具体来说是下载了index.js，krgetSign.js，krgetToken.js三个文件，在function目录下建立cache目录，把index.js放进去，另外两个文件直接放在function目录下。搞定。

**Comment by gbm777** [comment]
> 我按照之前说的删除并重新拉取的方法不成功。但是我根据日志得知是function目录下缺文件，我就搜索一些git上的相应文件并下载，最后成功解决该问题。具体来说是下载了index.js，krgetSign.js，krgetToken.js三个文件，在function目录下建立cache目录，把index.js放进去，另外两个文件直接放在function目录下。搞定。

问题来了，这3个文件去哪里下载呢？
