### ISSUE TITLE
脚本报错情况汇总

### ISSUE THREAD

**Issue by dong50252409** [shufflewzc/faker2#140]
我使用的是Arcadia

/arcadia/log/shufflewzc_faker2_jd_wechat_zz

> [2023-09-07 09:30:00:231] 执行开始
/usr/local/lib/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5109: Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when option 'module' is set to 'NodeNext'.
    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:863:19)
    at /usr/local/lib/node_modules/ts-node/src/index.ts:1379:34
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1451:13)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 5109 ]
}
[2023-09-07 09:30:01:100] 执行结束，总用时 1 秒

/arcadia/log/shufflewzc_faker2_jd_wsdlb
> [2023-09-07 12:05:00:082] 执行开始
🔔极速版我是大老板农场, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 12:05:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始【京东账号1】jd_7c3141f9082b4*********
❌ 极速版我是大老板农场, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'firstJoinFlag')!
🔔极速版我是大老板农场, 结束! 🕛 0.802 秒
[2023-09-07 12:05:00:983] 执行结束，总用时 0 秒

/arcadia/log/shufflewzc_faker2_jd_unsubscriLive
> [2023-09-06 22:55:00:054] 执行开始
🔔取关所有主播, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-6 22:55:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
****开始【京东账号1】jd_7c3141f9082b4*****
❗️取关所有主播, 错误!
TypeError: Cannot read properties of null (reading 'iRet')
    at /arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:177:26
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:253:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
****开始【京东账号2】jd_IEBetmKtEIWr*****
❗️取关所有主播, 错误!
TypeError: Cannot read properties of null (reading 'iRet')
    at /arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:177:26
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:253:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
****开始【京东账号3】jd_nGZrQsXHUSis*****
❗️取关所有主播, 错误!
TypeError: Cannot read properties of null (reading 'iRet')
    at /arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:177:26
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:253:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
****开始【京东账号4】jd_PdALOJyjffEi*****
❗️取关所有主播, 错误!
TypeError: Cannot read properties of null (reading 'iRet')
    at /arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:177:26
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_unsubscriLive.js:253:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

/arcadia/log/shufflewzc_faker2_jd_supermohe
> [2023-09-06 20:05:00:069] 执行开始
🔔超级盲盒, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-6 20:05:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始【京东账号1】jd_7c3141f9082b4*********
失败原因: undefined
/arcadia/repo/shufflewzc_faker2/jd_supermohe.js:261
        resolve(res);
                ^
ReferenceError: res is not defined
    at /arcadia/repo/shufflewzc_faker2/jd_supermohe.js:261:17
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_supermohe.js:344:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.17.1
[2023-09-06 20:05:00:587] 执行结束，总用时 0 秒

/arcadia/log/shufflewzc_faker2_jd_sgmh
> faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
【注意】本脚本默认会给助力池进行助力！
如需加入助力池请添加TG群：https://t.me/jd_zero_205
如不加入助力池互助，可添加变量名称：JD_JOIN_ZLC，变量值：false
开始获取闪购盲盒配置文件
共4个京东账号
您提供了0个账号的闪购盲盒助力码
当前使用助力池http://zlc1.chaoyi996.com:8880
第1个京东账号将要助力的好友["T0225KkcRksZpgDSIBj3xvADdQCjVWmIaW5kRrbA","T0225KkcRx0Q_AaCdRr1xf8DIQCjVWmIaW5kRrbA","T0205KkcPFd_vD2uSkCi3YhXCjVWmIaW5kRrbA"]
******开始【京东账号1】娜娜精品淘*********
❗️闪购盲盒, 错误!
TypeError: Cannot read properties of undefined (reading 'bizCode')
    at /arcadia/repo/shufflewzc_faker2/jd_sgmh.js:115:25
    at got.post.then.message (/arcadia/repo/shufflewzc_faker2/jd_sgmh.js:414:5694)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
当前使用助力池http://zlc1.chaoyi996.com:8880

/arcadia/log/shufflewzc_faker2_jd_necklace_6dy
> 🔔点点券-加密, 开始!
node:internal/modules/cjs/loader:1080
  throw err;
  ^
Error: Cannot find module './function/dylant.js'
Require stack:
- /arcadia/repo/shufflewzc_faker2/jd_necklace_6dy.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/arcadia/repo/shufflewzc_faker2/jd_necklace_6dy.js:8:4251)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/arcadia/repo/shufflewzc_faker2/jd_necklace_6dy.js' ]
}
Node.js v18.17.1
[2023-09-07 16:35:00:276] 执行结束，总用时 0 秒

/arcadia/log/shufflewzc_faker2_jd_mofangj
> [2023-09-07 01:09:00:054] 执行开始
🔔京东集魔方, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 1:09:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始【京东账号1】jd_7c3141f9082b4*********
集魔方 抽京豆 赢新品
❗️京东集魔方, 错误!
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /arcadia/repo/shufflewzc_faker2/jd_mofangj.js:121:56
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

/arcadia/log/shufflewzc_faker2_jd_mofang_ex
> [2023-09-07 17:43:00:054] 执行开始
🔔京东小魔方--兑换, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 17:43:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始【京东账号1】jd_7c3141f9082b4*********
❌ 京东小魔方--兑换, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'projectId')!
🔔京东小魔方--兑换, 结束! 🕛 3.216 秒
[2023-09-07 17:43:03:364] 执行结束，总用时 3 秒

> [2023-09-07 10:10:00:084] 执行开始
🔔特价版大赢家日常任务, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 10:10:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
开始领取任务奖励...
开始【账号1】jd_7c3141f9082b4
此CK可能黑了！
❗️特价版大赢家日常任务, 错误!
TypeError: Cannot read properties of null (reading '1')
    at /arcadia/repo/shufflewzc_faker2/jd_makemoneyshop_award.js:140:62
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_makemoneyshop_award.js:205:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
❌ 特价版大赢家日常任务, 失败! 原因: TypeError: $.tasklist is not iterable!
🔔特价版大赢家日常任务, 结束! 🕛 1.663 秒
[2023-09-07 10:10:01:873] 执行结束，总用时 1 秒

> [2023-09-07 11:03:00:062] 执行开始
🔔京东通天塔--签到, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 11:03:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始【京东账号1】jd_7c3141f9082b4*********
签到开始........
活动太火爆了
TypeError: Cannot read properties of null (reading '1')
    at /arcadia/repo/shufflewzc_faker2/jd_m_sign.js:94:81
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_m_sign.js:230:5721)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-07 11:03:03:183] 执行结束，总用时 3 秒

> 开始【京东账号1】jd_7c3141f9082b4
❗️京喜工厂商品列表详情, 错误!
TypeError: Cannot read properties of undefined (reading 'map')
    at EventEmitter.<anonymous> (/arcadia/repo/shufflewzc_faker2/jd_jxgckc.js:114:3743)
    at EventEmitter.emit (node:events:514:28)
    at fns.<computed> (/usr/local/lib/node_modules/got/dist/source/core/utils/proxy-events.js:7:16)
    at Request.emit (node:events:514:28)
    at Request._onResponseBase (/usr/local/lib/node_modules/got/dist/source/core/index.js:903:22)
    at Request._onResponse (/usr/local/lib/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (/usr/local/lib/node_modules/got/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)

> faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
目前已知领取一次 ，其他的未知。
******开始【京东账号1】jd_7c3141f9082b4*********
{"resultCode":-1,"resultMsg":"您调用的接口方法暂未找到，请检查业务类型，方法名，别名是否正确，或请联系接口相关负责人！","channelEncrypt":0}
❗️京东金融每周领取权益活动, 错误!
TypeError: Cannot read properties of undefined (reading 'data')
    at /arcadia/repo/shufflewzc_faker2/jd_jr_draws.js:82:51
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_jr_draws.js:213:5617)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

> 🔔汪汪乐园赛跑, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 20:03:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始【京东账号1】jd_7c3141f9082b4*********
成功 0
收益 0
成为队长
🧧 0
💊 0
⏳ 0分0秒
终点目标 0.01
Response code 403 (Forbidden)
Error TypeError: Cannot read properties of undefined (reading 'assets')
    at startRunning (/arcadia/repo/shufflewzc_faker2/jd_joy_park_run.js:15:23145)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/arcadia/repo/shufflewzc_faker2/jd_joy_park_run.js:15:18365)
    at async /arcadia/repo/shufflewzc_faker2/jd_joy_park_run.js:15:14982

> 
[2023-09-07 12:26:00:055] 执行开始
🔔宠汪汪喂食, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 12:26:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
*****开始【京东账号1】娜娜精品淘******
JDJR验证中......
evalmachine.<anonymous>:1
<!DOCTYPE html>
^
SyntaxError: Unexpected token '<'
    at new Script (node:vm:94:7)
    at createScript (node:vm:251:10)
    at Object.runInContext (node:vm:282:10)
    at IncomingMessage.<anonymous> (/arcadia/repo/shufflewzc_faker2/JDJRValidator_Pure.js:350:16)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
evalmachine.<anonymous>:1
<!DOCTYPE html>
^
SyntaxError: Unexpected token '<'
    at new Script (node:vm:94:7)
    at createScript (node:vm:251:10)
    at Object.runInContext (node:vm:282:10)
    at IncomingMessage.<anonymous> (/arcadia/repo/shufflewzc_faker2/JDJRValidator_Pure.js:350:16)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
❌ 宠汪汪喂食, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'validate')!
🔔宠汪汪喂食, 结束! 🕛 3.905 秒
[2023-09-07 12:26:04:051] 执行结束，总用时 4 秒

> [2023-09-07 00:00:30:063] 执行开始
No module named 'jd_sign'
请先运行Faker库依赖一键安装脚本(jd_check_dependent.py)，安装jd_sign.so依赖
已获取并使用Env环境 Cookie
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023/09/07 00:00:30=====================
Traceback (most recent call last):
  File "/arcadia/repo/shufflewzc_faker2/jd_jingBeanReceive.py", line 72, in <module>
    ua = userAgent()
         ^^^^^^^^^
NameError: name 'userAgent' is not defined
[2023-09-07 00:00:30:344] 执行结束，总用时 0 秒

> 🔔东东工厂内部互助, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 17:50:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
开始获取东东工厂内部互助配置文件
共4个京东账号
******开始【京东账号1】jd_7c3141f9082b4*********
❗️东东工厂内部互助, 错误!
TypeError: Cannot read properties of undefined (reading 'bizCode')
    at /arcadia/repo/shufflewzc_faker2/jd_jdfactory_help.js:170:27
    at got.post.then.message (/arcadia/repo/shufflewzc_faker2/jd_jdfactory_help.js:294:5772)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

> [2023-09-07 20:10:00:107] 执行开始
🔔东东工厂, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 20:10:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始【京东账号1】jd_7c3141f9082b4*********
❗️东东工厂, 错误!
TypeError: Cannot read properties of undefined (reading 'bizCode')
    at /arcadia/repo/shufflewzc_faker2/jd_jdfactory.js:607:27
    at got.post.then.message (/arcadia/repo/shufflewzc_faker2/jd_jdfactory.js:736:6688)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
❗️东东工厂, 错误!
TypeError: Cannot read properties of undefined (reading 'bizCode')
    at /arcadia/repo/shufflewzc_faker2/jd_jdfactory.js:444:27
    at got.post.then.message (/arcadia/repo/shufflewzc_faker2/jd_jdfactory.js:736:6688)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

> 🔔京洞察问卷通知, 开始!
====================共4个京东账号Cookie=========
==================脚本执行- 北京时间(UTC+8)：2023-9-7 15:35:00=====================
faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
******开始查询【京东账号1】jd_7c3141f9082b4*********
开始获取京洞察调研列表...
******开始查询【京东账号2】jd_IEBetmKtEIWr*********
开始获取京洞察调研列表...
❗️京洞察问卷通知, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /arcadia/repo/shufflewzc_faker2/jd_insight_Mod.js:136:19
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/arcadia/repo/shufflewzc_faker2/jd_insight_Mod.js:399:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
当前账户没有京调研问卷

> [2023-09-07 19:50:00:062] 执行开始
如果报错请在环境变量中添加你的真实 IP:端口
名称：IPPORT	值：127.0.0.1:5700
或在 config.sh 中添加 export IPPORT='127.0.0.1:5700'
===> 禁用重复任务开始 <===
加载推送功能中...
❌无法获取 token!!!
Traceback (most recent call last):
  File "/arcadia/repo/shufflewzc_faker2/jd_identicaln214.py", line 161, in get_token
    with open(path, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/ql/data/config/auth.json'
Traceback (most recent call last):
  File "/arcadia/repo/shufflewzc_faker2/jd_identicaln214.py", line 161, in get_token
    with open(path, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/ql/data/config/auth.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/arcadia/repo/shufflewzc_faker2/jd_identicaln214.py", line 173, in <module>
    token = get_token()
            ^^^^^^^^^^^
  File "/arcadia/repo/shufflewzc_faker2/jd_identicaln214.py", line 165, in get_token
    send("💔禁用重复任务失败", "无法获取 token!!!")
TypeError: 'NoneType' object is not callable
[2023-09-07 19:50:00:321] 执行结束，总用时 0 秒

额 报错的脚本是在太多了 是我配置的问题么 

```
repo:
  - name: "" # 仓库名称
    url: "" # 仓库远程地址
    branch: "" # 分支名称
    enable: true # 是否启用该仓库配置
    cronSettings:
      updateTaskList: false # 是否为该配置启用定时任务（默认不启用）
      scriptsPath: "" # 定时脚本路径（默认为仓库根目录）
      scriptsType: # 定时脚本文件格式（默认为 JavaScript、Python、TypeScript 脚本）
        - js
        - ts
        - py
      whiteList: '' # 定时脚本匹配白名单（默认为空，即所有脚本）
      blackList: '' # 定时脚本匹配黑名单（默认为空）
      autoDisable: false # 是否自动禁用新的定时任务
      addNotify: true # 是否为新增定时任务推送通知提醒
      delNotify: true # 是否为过期定时任务推送通知提醒
  - name: "Faker"
    url: "https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker2.git"
    branch: "main"
    enable: true
    cronSettings:
      updateTaskList: true
      scriptsPath: ''
      scriptsType:
        - js
        - py
        - ts
      whiteList: '^jd_|^jx_|^m_jd_'
      blackList: ''
      autoDisable: false
      addNotify: true
      delNotify: true
```

**Comment by testwhite** [comment]
已经解决了：https://www.playezu.com/766733.html

**Comment by shufflewzc** [comment]
已经解决了：https://www.playezu.com/766733.html
