### ISSUE TITLE
宠旺旺喂食报错

### ISSUE THREAD

**Issue by 1264116203** [shufflewzc/faker2#150]
## 开始执行... 2023-10-25 14:48:59

🔔宠汪汪喂食, 开始!
加载sendNotify，当前版本: 20230712
检测到一对一Uid文件WxPusherUid.json，载入...

====================共2个京东账号Cookie=================

============脚本执行时间：2023/10/25 14:49:01=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>>>

*****开始【京东账号1】INK许备备******

JDJR验证中......
evalmachine.<anonymous>:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at IncomingMessage.<anonymous> (/ql/scripts/shufflewzc_faker2_main/JDJRValidator_Pure.js:350:16)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
evalmachine.<anonymous>:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInContext (node:vm:288:10)
    at IncomingMessage.<anonymous> (/ql/scripts/shufflewzc_faker2_main/JDJRValidator_Pure.js:350:16)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

❌ 宠汪汪喂食, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'validate')!

🔔宠汪汪喂食, 结束! 🕛 6.321 秒

**Comment by leapyear1969** [comment]
同样有问题，你解决了吗？
