### ISSUE TITLE
[求解]失败! 原因: SyntaxError: Unexpected token '<'! 

### ISSUE THREAD

**Issue by dipck9954** [shufflewzc/faker2#197]
拉库后运行依赖安装完成，并浏览器手动获取JD_COOKIE的pt_key和pt_pin添加至环境变量，运行所有任务都报错，信息如下：

/ql/data/scripts/shufflewzc_faker2_main/sendNotify.js:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at new Notification (/ql/data/scripts/shufflewzc_faker2_main/utils/Rebels_sendJDNotify.js:30:7723)
    at Object.<anonymous> (/ql/data/scripts/shufflewzc_faker2_main/utils/Rebels_sendJDNotify.js:30:19027)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)

![5](https://github.com/shufflewzc/faker2/assets/170221676/8d0a1328-1120-4cc6-92ed-d97f74eb9947)

**Comment by shufflewzc** [comment]
看着像是文件错误，再拉一次库更新文件试试吧

**Comment by dipck9954** [comment]
重新拉了库，也更新了pt_key，每天只有一个无线端签到领京东的任务能成功
