### ISSUE TITLE
批量取关店铺和商品运行错误

### ISSUE THREAD

**Issue by AlephZHAO** [shufflewzc/faker2#206]
```
## 开始执行... 2024-08-01 11:02:52


🔔批量取关店铺和商品, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2024/08/01 11:02:53=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新 关注频道https://t.me/scriptalking>>>>>>>>>>>>>>>

"Response code 403 (Forbidden)"
批量取关店铺和商品 API请求失败，请检查网路重试

****开始【京东账号1】jd_XXXXXXX*****

无商品需要取关

当前已关注商品：0个
不执行取消收藏商品

正在获取已关注的店铺...

❗️批量取关店铺和商品, 错误!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/shufflewzc_faker2_main/jd_unsubscribe.js:76:63435
    at /ql/data/scripts/shufflewzc_faker2_main/jd_unsubscribe.js:323:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
不执行取消收藏店铺

【京东账号1】
【还剩关注店铺】0个
【还剩关注商品】0个

🔔批量取关店铺和商品, 结束! 🕛 11.207 秒


## 执行结束... 2024-08-01 11:03:04  耗时 12 秒　　　　　
```
日志如上，求解，已确认网路无误

**Comment by shufflewzc** [comment]
@AlephZHAO 403,进群看代理教程

**Comment by AlephZHAO** [comment]
> @AlephZHAO 403,进群看代理教程

好的，谢谢！
