### ISSUE TITLE
自动评价出错

### ISSUE THREAD

**Issue by dlNone** [shufflewzc/faker2#58]
socket hang up
TypeError: Cannot read properties of undefined (reading 'maxPage')
    at main (/ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:16220)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:13600
冷却中...

**Comment by weishaopenggege** [comment]
> socket hang up TypeError: Cannot read properties of undefined (reading 'maxPage') at main (/ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:16220) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:13600 冷却中...

我也报一样的错, 坐等大佬修复

**Comment by shufflewzc** [comment]
> > socket hang up TypeError: Cannot read properties of undefined (reading 'maxPage') at main (/ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:16220) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:13600 冷却中...
> 
> 
> 
> 我也报一样的错, 坐等大佬修复

再跑一下就行 网络问题

**Comment by BytePrince** [comment]
> > > socket hang up TypeError: Cannot read properties of undefined (reading 'maxPage') at main (/ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:16220) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /ql/data/scripts/shufflewzc_faker2_main/jd_autocomment.js:6:13600 冷却中...
> > 
> > 
> > 我也报一样的错, 坐等大佬修复
> 
> 再跑一下就行 网络问题

请问现在autocomment.js移除了吗？我重装了一下容器，再拉库发现autocomment.js已经没了

**Comment by zhangqx1** [comment]
read ECONNRESET

❌ 自动评价, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'maxPage')!

我也是
