### ISSUE TITLE
一键安装依赖脚本运行报错，求大佬解答

### ISSUE THREAD

**Issue by RobertXJi** [shufflewzc/faker2#87]
Traceback (most recent call last):
  File "/ql/data/scripts/shufflewzc_faker3_main/jd_check_dependent.py", line 20, in <module>
    import requests, os, platform
ModuleNotFoundError: No module named 'requests'

**Comment by chenjingchun** [comment]
我也这样
Traceback (most recent call last):
  File "/ql/data/scripts/shufflewzc_faker2_main/jd_check_dependent.py", line 20, in <module>
    import requests, os, platform
ModuleNotFoundError: No module named 'requests'

**Comment by fxxisme** [comment]
把脚本里面的代理去掉 `proxy.zyun.vip`
