### ISSUE TITLE
获取互助码失败

### ISSUE THREAD

**Issue by chenjingchun** [shufflewzc/faker2#91]
运行task shufflewzc_faker2_main/jd_get_share_code.js
错误如下，我这是哪里配置的不对吗，感谢解答：

====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2023-2-2 16:19:11=====================

faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking

注：临时活动的互助码不添加到此处，如有需要请手动运行对应临时活动脚本

======账号1开始======
【京东账号1（1924286-15996316）京东农场】5e39110c07b34da882e717883e33f487
shit
【京东账号1（1924286-15996316）种豆得豆】ky2zyakuys6vq3jbvr4egufq433bx5jw7dknjay
【京东账号1（1924286-15996316）东东工厂】T022v_RxRBwR80nWJRP9kvQLcgCjVWnYaS5kRrbA
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at safeGet (/ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:611:21)
    at /ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:129:17
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:701:4869)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
京东服务器访问数据为空，请检查自身设备网络情况
GetUserInfo异常："<!DOCTYPE html><html lang=\"zh-CN\"><head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;\">\n    <title>出错了</title>\n    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\n    <meta name=\"format-detection\" content=\"telephone=no\">\n\n    <link rel=\"stylesheet\" href=\"//wq.360buyimg.com/fd/h5/wxsq_dev/errorPage/css/index.min_d70d24fe.css\">\n    <meta name=\"format-detection\" content=\"telephone=no\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no, viewport-fit=cover\">\n<meta http-equiv=\"x-dns-prefetch-control\" content=\"on\" />\n<link rel=\"dns-prefetch\" href=\"//img10.360buyimg.com\">\n<link rel=\"dns-prefetch\" href=\"//img11.360buyimg.com\">\n<link rel=\"dns-prefetch\" href=\"//img12.360buyimg.com\">\n<link rel=\"dns-prefetch\" href=\"//img13.360buyimg.com\">\n<link rel=\"dns-prefetch\" href=\"//img14.360buyimg.com\">\n<link rel=\"dns-prefetch\" href=\"//img20.360buyimg.com\">\n<link rel=\"dns-prefetch\" href=\"//img30.360buyimg.com\">\n<link rel=\"dns-prefetch\" href=\"//wq.360buyimg.com\">\n<script type=\"text/javascript\">\nfunction __reloadResource(c){try{var l=document.head||document.getElementsByTagName(\"head\")[0];var b=window._oss_path||\"wq.360buyimg.com\";var d=window._oss_path||/img\\d{1,2}.360buyimg.com/;if(c&&/link/i.test(c.tagName)){if(!c.href||c.href.indexOf(b)==-1){return}var a=document.createElement(\"link\");a.rel=\"stylesheet\";a.href=c.href.replace(b,\"wqimg.jd.com\");l.appendChild(a)}if(c&&/script/i.test(c.tagName)){if(!c.src||c.src.indexOf(b)==-1){return}var e=document.createElement(\"script\");e.type=\"text/javascript\";e.src=c.src.replace(b,\"wqimg.jd.com\");l.appendChild(e)}if(c&&/img/i.test(c.tagName)){if(!c.src||!d.test(c.src))…………………………

❗️获取互助码, 错误!
TypeError: Cannot read properties of undefined (reading 'bizCode')
    at /ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:499:25
    at got.post.then.message (/ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:701:5772)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
【京东账号1（1924286-15996316）签到领现金】IhI1aO66YOEn9GfczXAS0A
======账号1结束======

🔔获取互助码, 结束! 🕛 8.009 秒

**Comment by cn-404-not-found** [comment]
我也是这样

**Comment by Doublefire-Chen** [comment]
Same issue
