### ISSUE TITLE
京东极速版红包(jd_speed_redpocke.js) 签到异常

### ISSUE THREAD

**Issue by ilihu** [shufflewzc/faker2#93]
日志如下，试了多次依旧无效

```
## 开始执行... 2023-02-06 22:57:01


🔔京东极速版红包, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2023-2-6 22:57:03=====================

faker 友情提示：您的脚本正常运行中

如提示活动火爆,可再执行一次尝试


🔔京东极速版红包, 结束! 🕛 1.277 秒


******开始【京东账号1】faker1*********

极速版签到提现：签到异常:{"code":"1","echo":"no access"}

undefined
undefined
undefined

如提示活动火爆,可再执行一次尝试


******开始【京东账号2】faker2*********

极速版签到提现：签到异常:{"code":"1","echo":"no access"}

undefined
undefined
undefined


## 执行结束... 2023-02-06 22:57:37  耗时 36 秒
```

再次执行，依旧出错

```
## 开始执行... 2023-02-07 00:12:37


🔔京东极速版红包, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2023-2-7 0:12:39=====================

faker 友情提示：您的脚本正常运行中

如提示活动火爆,可再执行一次尝试


🔔京东极速版红包, 结束! 🕛 1.499 秒


******开始【京东账号1】faker1*********

Parse Error: Invalid header value char
极速版签到提现：签到异常:{"code":"1","echo":"no access"}

Parse Error: Invalid header value char
undefined
Parse Error: Invalid header value char
undefined
Parse Error: Invalid header value char
undefined

如提示活动火爆,可再执行一次尝试


❗️京东极速版红包, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/shufflewzc_faker2_main/jd_speed_redpocke.js:26:89183
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/data/scripts/shufflewzc_faker2_main/jd_speed_redpocke.js:27:4869)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

******开始【京东账号2】faker2*********

Parse Error: Invalid header value char
极速版签到提现：签到异常:{"code":"1","echo":"no access"}

Parse Error: Invalid header value char
undefined
undefined
undefined


## 执行结束... 2023-02-07 00:13:00  耗时 23 秒
```

我cookie都正确填写在环境变量中，执行其他脚本都可以正常运行。
你们最近出现过这种情况吗？

**Comment by shufflewzc** [comment]
估计是黑了
