### ISSUE TITLE
禁用重复任务执行出错

### ISSUE THREAD

**Issue by iulo** [shufflewzc/faker2#95]
日志如下：
```
## 开始执行... 2023-02-14 22:09:25

===> 禁用重复任务开始 <===
加载推送功能中...

=== 你选择过滤的任务前缀为 ===
shufflewzc_faker2_main
Traceback (most recent call last):
  File "/ql/data/scripts/shufflewzc_faker2_main/jd_identical.py", line 192, in <module>
    filter_list, res_list = filter_res_sub(tasklist)
  File "/ql/data/scripts/shufflewzc_faker2_main/jd_identical.py", line 70, in filter_res_sub
    if task.get("command").find(sub) == -1:
AttributeError: 'str' object has no attribute 'get'


## 执行结束... 2023-02-14 22:09:26  耗时 1 秒
```

**Comment by shufflewzc** [comment]
最新青龙不行，余下的按照版本跑就可以
